### ISSUE TITLE
bnb 转账报error message = "replacement transaction underpriced"

### ISSUE THREAD

**Issue by wudonghui29** [JianBinWu/Wallet#5]
您好，bnb 转账报error message = "replacement transaction underpriced"， 麻烦你帮忙看下。方便加下你的微信吗？我的微信a516090546。

**Comment by wudonghui29** [comment]
eth 转账是正常的

**Comment by JianBinWu** [comment]
尝试把gas费用设高一点试一下

**Comment by JianBinWu** [comment]
> 您好，bnb 转账报error message = "replacement transaction underpriced"， 麻烦你帮忙看下。方便加下你的微信吗？我的微信a516090546。

尝试把gas费用设高一点试一下

**Comment by wudonghui29** [comment]
> > 您好，bnb 转账报error message = "replacement transaction underpriced"， 麻烦你帮忙看下。方便加下你的微信吗？我的微信a516090546。
> 
> 尝试把gas费用设高一点试一下

你好，我尝试了把gas费用设高，第一次设置提示转账成功，但是实际上没有。第二次又报相同的错误"replacement transaction underpriced"

**Comment by JianBinWu** [comment]
> > > 您好，bnb 转账报error message = "replacement transaction underpriced"， 麻烦你帮忙看下。方便加下你的微信吗？我的微信a516090546。
> > 
> > 
> > 尝试把gas费用设高一点试一下
> 
> 你好，我尝试了把gas费用设高，第一次设置提示转账成功，但是实际上没有。第二次又报相同的错误"replacement transaction underpriced"

你是使用测试网络吗，可以把你的地址发给我，我用这个功能给你转一笔试一下，我自己试用转账是没问题的

**Comment by wudonghui29** [comment]
> 
我用的是主网，bnb的测试网络怎么充币？我没用过。我对这块不太懂，方不方便加个微信，问你几个小问题，不剩感激！

**Comment by JianBinWu** [comment]
主网的话需要把代码里的isMainNet变量改成true再试下，测试网可以通过https://testnet.binance.org/faucet-smart这个网址充币



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 下午3:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JianBinWu/Wallet-iOS] bnb 转账报error message = &quot;replacement transaction underpriced&quot; (Issue #5)





   
我用的是主网，bnb的测试网络怎么充币？我没用过。我对这块不太懂，方不方便加个微信，问你几个小问题，不剩感激！

**Comment by wudonghui29** [comment]
> 主网的话需要把代码里的isMainNet变量改成true再试下，测试网可以通过[https://testnet.binance.org/faucet-smart这个网址充币](https://testnet.binance.org/faucet-smart%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%E5%85%85%E5%B8%81)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年8月24日(星期三) 下午3:38 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [JianBinWu/Wallet-iOS] bnb 转账报error message = &quot;replacement transaction underpriced&quot; (Issue #5) 我用的是主网，bnb的测试网络怎么充币？我没用过。我对这块不太懂，方不方便加个微信，问你几个小问题，不剩感激！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by wudonghui29** [comment]
我一直就是把isMainNet变量改成了true的，转账部分的代码什么也没动，eth可以转，bnb就是不行，报这个错"replacement transaction underpriced"。我刚才改为false, 然后在你给我的网站充了0.5，要不你转给我这个地址0x511c7be51eb7dff4e33cd3b54b69bd5f53eb73ed，谢谢了！

**Comment by JianBinWu** [comment]
转了，你看一下，测试网的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 下午4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JianBinWu/Wallet-iOS] bnb 转账报error message = &quot;replacement transaction underpriced&quot; (Issue #5)





 
我一直就是把isMainNet变量改成了true的，转账部分的代码什么也没动，eth可以转，bnb就是不行，报这个错"replacement transaction underpriced"。我刚才改为false, 然后在你给我的网站充了0.5，要不你转给我这个地址0x511c7be51eb7dff4e33cd3b54b69bd5f53eb73ed，谢谢了！

**Comment by wudonghui29** [comment]
你是不是转了0.1？我这边转报另外一个错message = "transaction underpriced"

**Comment by JianBinWu** [comment]
手续费改高一点，改成0.001



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JianBinWu/Wallet-iOS] bnb 转账报error message = &quot;replacement transaction underpriced&quot; (Issue #5)





 
你是不是转了0.1？我这边转报另外一个错message = "transaction underpriced"

**Comment by wudonghui29** [comment]
手续费改成0.001就转账成功了，余额减了。手续费一定要大于0.001吗？

**Comment by JianBinWu** [comment]
不一定，一般有专门获取手续费的接口，按照推荐的手续费来就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 下午4:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JianBinWu/Wallet-iOS] bnb 转账报error message = &quot;replacement transaction underpriced&quot; (Issue #5)





 
手续费改成0.001就转账成功了，余额减了。手续费一定要大于0.001吗？

**Comment by wudonghui29** [comment]
从自己服务器的接口获取手续费吗？现在代码里面是最小的21000

**Comment by JianBinWu** [comment]
网上有平台提供接口，你可以自己找一下，https://www.liaoxuefeng.com/wiki/1207298049439968/1207319614454336你可以看看这个老师讲的有关矿工费的概念



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JianBinWu/Wallet-iOS] bnb 转账报error message = &quot;replacement transaction underpriced&quot; (Issue #5)





 
从自己服务器的接口获取手续费吗？现在代码里面是最小的21000

**Comment by wudonghui29** [comment]
好的，非常感谢你了！

**Comment by JianBinWu** [comment]
不客气



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JianBinWu/Wallet-iOS] bnb 转账报error message = &quot;replacement transaction underpriced&quot; (Issue #5)





 
好的，非常感谢你了！
